### ISSUE TITLE
[RFC] Allow user-defined home directory

### ISSUE THREAD

**Issue by aramalipoor** [farmer-project/farmer#35]
Add an option in `.farmer.yml` to allow user to choose a directory different than `/app` to be root of their source code.

e.g. Like below
```yaml
image: myorg/myapp:tag
home: /mydir # This is a user-defined home for the source code.
ports:
  - 22/tcp
  - 80/tcp
scripts:
  create: "devops/production/bin/install"
  deploy: "devops/production/bin/update"
```
