### ISSUE TITLE
[RFC] Allow user to define custom scripts and run them manually

### ISSUE THREAD

**Issue by aramalipoor** [farmer-project/farmer#47]
Alongside our system-defined scripts (such as `create` and `deploy`) let users define their own script tags and run them manually when they need it.

Take this example `.farmer.yml`
```yaml
image: myorg/myapp:tag
ports:
  - 80/tcp
scripts:
  create: "devops/production/bin/install"
  deploy: "devops/production/bin/update"
  clearCache: "devops/production/bin/clear-cache"
```

You shall run command below for their custom script:
```sh
farmer-cli run asrdigital --script=clearCache
```
