### ISSUE TITLE
[RFC] Staging new source code before running "deploy" command

### ISSUE THREAD

**Issue by aramalipoor** [farmer-project/farmer#56]
When user issues a deploy command it would be great if Farmer would run a staging process before deploying on the already **running** production container so that we can have a fail-safe deployment on boxes.

So the `deploy` process would be as follows:

1. User runs `farmer-cli deploy boxname1 -p tags/2.0` on a box currently on `tags/0.1` pathspec.
2. Farmer clones `boxname1` container completely as is in production.
3. Checks out `tags/2.0` source code on *cloned* box.
4. Runs `deploy` script defined in .farmer.yml.
5. Runs `status` script defined in .farmer.yml and **depending on status script exit code** it determines if the deploy was successfully done with no errors.
 * If status script returned **0 exit code** box will be updated to the new deployed container.
 * If status script returned a different exit code it leaves production box as is, and shows the error to the user.

Below is a sample `.farmer.yml` with status script:
```yaml
image: myorg/myapp:tag
ports:
  - 80/tcp
scripts:
  create: "devops/production/bin/install"
  deploy: "devops/production/bin/update"
  status: "devops/production/bin/status"
```
