### ISSUE TITLE
[RFC] Add a shared files/dirs config to keep consistent between revisions

### ISSUE THREAD

**Issue by aramalipoor** [farmer-project/farmer#66]
If we introduce a `shared` config, we can only copy these files/dirs between deploys (revisions).

Take this example `.farmer.yml`
```yaml
image: myorg/myapp:tag
ports:
  - 80/tcp
shared:
  - app/config/parameters.yml
  - app/Resources/settings.yml
  - web/media/*
scripts:
  create: "devops/create"
  deploy: "devops/deploy"
```
